import rr.Text
import Db

Ui :: [].{
	YLabel : { p : Text.Prepared, v : F32 }
	EndLabel : { p : Text.Prepared, sel : U8 }

	Model : {
		title : Text.Prepared,
		subs : List({ p : Text.Prepared, r : U64, chip : Text.Prepared }),
		leg_fit : Text.Prepared,
		leg_fat : Text.Prepared,
		leg_form : Text.Prepared,
		ylabels : List(YLabel),
		ends : List(EndLabel),
		ev_label : Text.Prepared,
		ev_found : Bool,
		ev_idx : U64,
		ev_warn : Text.Prepared,
		ev_warn_found : Bool,
		stale : Text.Prepared,
		stale_found : Bool,
		view : U8,
		curve : List(Db.CurvePt),
		curve_lbls : List({ p : Text.Prepared, d : I64 }),
		fit_lbl : Text.Prepared,
		curve_title : Text.Prepared,
		curve_hint : Text.Prepared,
		trace_hint : Text.Prepared,
		table_hint : Text.Prepared,
		table_title : Text.Prepared,
		table_head : List(Text.Prepared),
		kpis : List({ v : Text.Prepared, cap : Text.Prepared, sel : U8 }),
		ev_tile_top : Text.Prepared,
		ev_tile_sub : Text.Prepared,
		zero_note : Text.Prepared,
		ridden_found : Bool,
		ridden_note : Text.Prepared,
		curve_empty : Text.Prepared,
		trace : List(F32),
		segs : List(Db.Seg),
		trace_title : Text.Prepared,
		trace_dur : F32,
		trace_ids : List({ id : I64, day : Str }),
		trace_sel : U64,
		trace_day : Str,
		curve_days : I64,
		fit_cp : F32,
		cp_lbl : Text.Prepared,
		data : List(Db.Point),
		days : List(Str),
		day_notes : List({ day : Str, note : Str }),
		home : Str,
		tick : U64,
		last_focus : { view : I64, range : I64, cursor_day : Str, trace_day : Str },
		status : Text.Prepared,
		has_error : Bool,
		font : Text.Font,
		hint : Text.Prepared,
		empty : Text.Prepared,
		range : U64,
		mouse_x : F32,
		mouse_y : F32,
		win : { w : F32, h : F32 },
		detail_day : Str,
		detail : List(Str),
		mouse_in : Bool,
		cursor : I64,
	}
}
