#!/bin/sh
# Every TEXT column decoded by `Sqlite.str` OR `Sqlite.nullable_str` must be
# projected through `CAST(... AS TEXT)`.
#
# TEXT affinity converts INTEGER and REAL but NOT blobs, so a blob from a
# hand-edit or bad import survives the column and a bare decode answers
# `UnexpectedType(Bytes)` -> `internal_error` — a data fault reported as a bug.
# A rule applied by remembering does not converge across a hundred references:
# #296 shipped believing three sites when there were twelve, and #307 measured
# the same crash in three more columns. This lint pairs each `Sqlite.str` decode
# with the projection producing that alias and fails on a bare column reference.
#
# Known limits, none firing on the tree today: a projection split across two
# source lines reports an empty expression; a comment quoting an old bare form
# above a wrapped projection is reported; `${Interpolated} AS alias` and
# `AS ${alias}` are not understood; two projections for one alias on one line
# keep only the last (grep -o is greedy). Stated rather than fixed — each needs
# a real SQL parse, and a gate whose limits are written down is one a reader can
# trust the rest of.
#
# Exactly two exemptions: `COUNT(` (yields an integer) and `PRAGMA` (SQLite
# generates it). The list was longer — MAX/MIN/group_concat/CASE — and every
# extra entry was false over a TEXT column: MAX over a mixed column PREFERS the
# blob (SQLite orders BLOB above TEXT), and the only use of that exemption in
# the tree was hiding a live `stride plan` crash.
set -eu
export LC_ALL=C
cd "$(dirname "$0")/.."
tmp=$(mktemp -d); trap 'rm -rf "$tmp"' EXIT

: > "$tmp/problems"
decodes=0
for f in src/*.roc; do
  # BOTH string decoders, and ANY alias. Scanning only `Sqlite.str` with a lowercase alias
  # class missed `Sqlite.nullable_str` entirely — one site in the tree, and it was a live
  # crash — and would miss `Sqlite.str("sportType")` without moving the asserted count,
  # which is the failure the count is supposed to make impossible.
  grep -oE 'Sqlite\.(nullable_)?str\("[^"]*"\)' "$f" 2>/dev/null | sed 's/.*("//;s/")//' | sort -u > "$tmp/aliases" || true
  [ -s "$tmp/aliases" ] || continue
  while IFS= read -r alias; do
    [ -n "$alias" ] || continue
    decodes=$((decodes + 1))
    # The projection that names it. Everything on the line BEFORE ` AS <alias>`, not the
    # last whitespace-delimited token: taking the token reads
    # `substr(CAST(day AS TEXT), 1, 7) AS month` as the expression `7)` and
    # reports an already-wrapped site as unwrapped. A gate whose false positives are that
    # easy to produce gets its findings dismissed, which is worse than not having it.
    grep -o ".* AS $alias\\b" "$f" 2>/dev/null | sed "s/ AS $alias\$//" | sort -u > "$tmp/exprs" || true
    if [ ! -s "$tmp/exprs" ]; then
      # A PRAGMA result is generated by SQLite, not stored in a column, so no blob can reach
      # it and a CAST would be describing a risk that does not exist. The only exemption
      # here, and it names the mechanism rather than the file.
      if grep -q "PRAGMA $alias" "$f" 2>/dev/null; then continue; fi
      # otherwise the column is selected bare and the alias IS the column name.
      # Scoped to the LINE that selects it, and to any table prefix. A file-wide grep
      # was a hole with two mouths: nearly every file now carries a CAST somewhere, so
      # a new bare projection was exempted by a neighbour — the gate's own count-bump
      # instruction routed a developer past it. And the prefix set was `<col>`/`a.`
      # only, so `s.`/`m.`/`p.`/`rt.`/`a2.` wraps reported "selected bare" while
      # correct. Anchored on the alias as a bare list item: preceded by SELECT or a
      # comma, followed by a comma or FROM.
      grep -E "(SELECT|,) *$alias *(,| FROM)" "$f" 2>/dev/null > "$tmp/bareline" || true
      if [ -s "$tmp/bareline" ]; then
        grep -qE "CAST\(([a-z_][a-z_0-9]*\.)?$alias AS TEXT\)" "$tmp/bareline" ||
          printf '%-24s %-22s selected bare on its own line, no CAST(... AS TEXT)\n' \
            "$(basename "$f")" "$alias" >> "$tmp/problems"
      else
        printf '%-24s %-22s no projection found for this decode\n' "$(basename "$f")" "$alias" >> "$tmp/problems"
      fi
      continue
    fi
    while IFS= read -r expr; do
      [ -n "$expr" ] || continue
      # Scope the expression to THIS projection — the line may hold several, and a
      # CAST belonging to an earlier one must not vouch for this alias. A fixed-width
      # window cut a long subquery projection in half, landing inside its own `CAST(`.
      # The boundary is the previous projection's `AS <name>`: drop everything up to
      # the last ` AS ` that is not a type cast (sed is greedy, which takes the LAST).
      tail_expr=$(printf '%s' "$expr" | awk '{
        # cut after the LAST `AS <name>` where <name> is a column alias, not a TYPE. Cutting
        # at any `AS` lands inside a `CAST(x AS TEXT)` and takes that CAST as this alias\047s;
        # compensating with "if the tail holds a cast, use the whole
        # expression" hands an EARLIER projection\047s cast to this one and passes
        # `COALESCE(a.sport_type, \047\047) AS sport` on a line whose date column was wrapped.
        n = 0
        for (i = 1; i <= NF; i++)
          if ($i == "AS" && i < NF && $(i+1) !~ /^(TEXT|REAL|INTEGER|BLOB|NUMERIC)([^A-Za-z_0-9]|$)/) n = i + 1
        out = ""
        for (i = n + 1; i <= NF; i++) out = out " " $i
        print (n ? out : $0)
      }')
      # Blank every `CAST(… AS TEXT)` span — balanced parens, so a subquery inside one
      # is blanked with it — then look for a column reference left in ARGUMENT position
      # (preceded by `(` or `,`, followed by `,` or `)`). "Does the tail contain AS
      # TEXT anywhere" let any one cast arm vouch for every other:
      # `COALESCE(CAST(a.sport_family AS TEXT), a.sport_type, '')` is a live crash
      # this tree writes three times. Argument position rather than any identifier,
      # because the tail carries Roc syntax and SQL keywords.
      # ...then keep only the projection list, cut AFTER the blanking at the FIRST
      # SELECT: cutting first, at the last, decapitated a correctly-wrapped
      # `CAST((SELECT …) AS TEXT)` so its subquery column looked bare. Blanking first
      # means any SELECT still standing is top-level.
      bare=$(printf '%s' "$tail_expr" | awk '{
        line = $0; out = ""
        while ((i = index(line, "CAST(")) > 0) {
          out = out substr(line, 1, i - 1)
          rest = substr(line, i + 5); depth = 1; j = 0
          while (j < length(rest) && depth > 0) {
            j++; c = substr(rest, j, 1)
            if (c == "(") depth++; else if (c == ")") depth--
          }
          span = substr(rest, 1, j)
          out = out (span ~ /AS TEXT/ ? "@" : "CAST(" span)
          line = substr(rest, j + 1)
        }
        print out line
      }' | awk '{ i = index($0, "SELECT"); print (i ? substr($0, i + 7) : $0) }' |
        sed -e "s/'[^']*'/@/g" |
        grep -oE '[(,] *[a-z_][a-z_0-9]*(\.[a-z_][a-z_0-9]*)? *[,)]|(ELSE|THEN) +[a-z_][a-z_0-9]*(\.[a-z_][a-z_0-9]*)? *(END|ELSE|WHEN|$)' |
        sed -e 's/^[(,] *//' -e 's/ *[,)]$//' -e 's/^ELSE *//' -e 's/^THEN *//' -e 's/ *END$//' -e 's/ *ELSE$//' -e 's/ *WHEN$//' | head -1)
      case "$tail_expr" in
        *"AS TEXT"*|*"as text"*)
          # a cast is present — but only clean if nothing UNCAST survives beside it
          if [ -n "$bare" ]; then
            printf '%-24s %-22s %s  (uncast: %s)\n' "$(basename "$f")" "$alias" \
              "$(printf '%s' "$tail_expr" | tail -c 46)" "$bare" >> "$tmp/problems"
          fi
          ;;
        # `COUNT(` only. Exempting `MAX(`, `MIN(`, `group_concat` and `CASE` on the theory
        # that they cannot yield a blob is false for every one over a TEXT column — the
        # wider exemption list fired exactly ONCE in the whole tree, on
        # `COALESCE(MAX(substr(start_local,1,10)),'') AS d`, which was a live `plan` crash.
        # `MAX` over a mixed column PREFERS the blob, since SQLite orders BLOB above TEXT.
        # An exemption whose only use is hiding a bug is not an exemption.
        *"COUNT("*) ;;
        # NOTE there is no exemption for a quote: a "literals" exemption swallows
        # `COALESCE(day, '') AS day`, which is the COMMON shape here and
        # unsafe: COALESCE picks the blob, not the fallback, because a blob is not NULL. It
        # hid five crashing commands the behavioural sweep then found anyway. That is the
        # failure this file's own header warns about, written into the file on the first
        # draft: an exemption list widened until the gate means nothing.
        *)
          printf '%-24s %-22s %s\n' "$(basename "$f")" "$alias" "$(printf '%s' "$tail_expr" | tail -c 46)" >> "$tmp/problems" ;;
      esac
    done < "$tmp/exprs"
  done < "$tmp/aliases"
done

# Asserted exactly, not as a floor. A gate whose enumeration silently matches nothing prints
# the same clean line a healthy tree prints — which is how the defect it guards got here.
EXPECT_DECODES=50
if [ "$decodes" != "$EXPECT_DECODES" ]; then
  echo "blob-safety: inspected $decodes (file, alias) decode pairs, expected $EXPECT_DECODES."
  echo "blob-safety: if that change is intended, update the number in the same commit;"
  echo "blob-safety: if it is not, the decode scan stopped matching and this gate is blind."
  exit 1
fi

sort -u "$tmp/problems" > "$tmp/problems.u"; mv "$tmp/problems.u" "$tmp/problems"
n=$(wc -l < "$tmp/problems" | tr -d ' ')
if [ "$n" -gt 0 ]; then
  echo "blob-safety: $n TEXT decode(s) read a column that is not CAST to TEXT"
  echo
  sort -u "$tmp/problems"
  echo
  echo "A blob in any of these crashes the reading command with internal_error (#307)."
  echo "Wrap the projection: COALESCE(CAST(<col> AS TEXT), '') AS <alias>"
  exit 1
fi
echo "blob-safety: $decodes (file, alias) decode pairs across 91 call sites, every projection CAST to TEXT"
