#!/bin/sh
# Every TEXT column decoded by `Sqlite.str` must be projected through `CAST(... AS TEXT)`.
#
# SQLite's TEXT affinity converts INTEGER and REAL but NOT blobs, so a blob written by a
# hand-edit, a partial corruption or a bad import survives in a TEXT column — and a bare
# `Sqlite.str` decode answers `UnexpectedType(Bytes)`, which the top level reports as
# `internal_error`: "this is a bug, not the data and not the invocation", about a fault that
# is entirely the data. `src/Db.roc` decided that rule for `config.value` and wrote down the
# reasoning; #296 applied it to `activities.start_local` across twelve sites.
#
# It did not converge, and could not have. #296 shipped believing there were three sites when
# there were five, then five when there were twelve — found by planting a blob and running
# every command, not by reading, because there are over a hundred references to that column
# across a dozen files. #307 then measured the same failure in three more columns:
# `activities.sport_type` (7 commands), `daily_load.day` (5), `activities.name` (3).
#
# A rule applied by remembering does not converge across a hundred sites. This is the lint
# the issue asks for: it pairs each `Sqlite.str("alias")` decode with the projection that
# produces that alias, and fails when the projection is a bare column reference. Forgetting
# becomes visible instead of becoming an `internal_error` months later.
#
# What it deliberately does NOT flag: an alias produced by an expression that cannot yield a
# blob — a literal, a `COUNT(*)`, a `group_concat`, a `CASE` over integers. Those are listed
# as derived and skipped, because demanding a CAST there would be noise, and a gate that
# cries wolf gets its exemption list widened until it means nothing.
set -eu
export LC_ALL=C
cd "$(dirname "$0")/.."
tmp=$(mktemp -d); trap 'rm -rf "$tmp"' EXIT

: > "$tmp/problems"
decodes=0
for f in src/*.roc; do
  # every `Sqlite.str("alias")` in this file
  grep -o 'Sqlite\.str("[a-z_0-9]*")' "$f" 2>/dev/null | sed 's/.*("//;s/")//' | sort -u > "$tmp/aliases" || true
  [ -s "$tmp/aliases" ] || continue
  while IFS= read -r alias; do
    [ -n "$alias" ] || continue
    decodes=$((decodes + 1))
    # The projection that names it. Everything on the line BEFORE ` AS <alias>`, not the
    # last whitespace-delimited token: a first cut took the token and read
    # `substr(CAST(a.start_local AS TEXT), 1, 7) AS month` as the expression `7)`, then
    # reported an already-wrapped site as unwrapped. A gate whose false positives are that
    # easy to produce gets its findings dismissed, which is worse than not having it.
    grep -o ".* AS $alias\\b" "$f" 2>/dev/null | sed "s/ AS $alias\$//" | sort -u > "$tmp/exprs" || true
    if [ ! -s "$tmp/exprs" ]; then
      # A PRAGMA result is generated by SQLite, not stored in a column, so no blob can reach
      # it and a CAST would be describing a risk that does not exist. The only exemption
      # here, and it names the mechanism rather than the file.
      if grep -q "PRAGMA $alias" "$f" 2>/dev/null; then continue; fi
      # otherwise the column is selected bare and the alias IS the column name
      grep -q "CAST($alias AS TEXT)\|CAST(a\.$alias AS TEXT)" "$f" 2>/dev/null ||
        printf '%-24s %-22s selected bare, no CAST(... AS TEXT)\n' "$(basename "$f")" "$alias" >> "$tmp/problems"
      continue
    fi
    while IFS= read -r expr; do
      [ -n "$expr" ] || continue
      # Scope the expression to THIS projection. The line may hold several, and a CAST
      # belonging to an earlier one must not vouch for this alias — but a fixed-width window
      # is the wrong rule for that: a 90-character tail cut a long subquery projection in
      # half, landing inside its own `CAST(`, and reported an already-wrapped site.
      #
      # The boundary is the previous projection's `AS <name>`, so drop everything up to the
      # last ` AS ` that is not a type cast. `sed` is greedy, which is what makes it take
      # the LAST one.
      tail_expr=$(printf '%s' "$expr" | awk '{
        # cut after the LAST `AS <name>` where <name> is a column alias, not a TYPE. Cutting
        # at any `AS` lands inside a `CAST(x AS TEXT)` and takes that CAST as this alias\047s;
        # a first version compensated with "if the tail holds a cast, use the whole
        # expression", which handed an EARLIER projection\047s cast to this one and passed
        # `COALESCE(a.sport_type, \047\047) AS sport` on a line whose date column was wrapped.
        n = 0
        for (i = 1; i <= NF; i++)
          if ($i == "AS" && i < NF && $(i+1) !~ /^(TEXT|REAL|INTEGER|BLOB|NUMERIC)([^A-Za-z_0-9]|$)/) n = i + 1
        out = ""
        for (i = n + 1; i <= NF; i++) out = out " " $i
        print (n ? out : $0)
      }')
      case "$tail_expr" in
        *CAST*) ;;                                   # already wrapped
        *"COUNT("*|*"SUM("*|*"MAX("*|*"MIN("*) ;;    # aggregates over non-text
        *"group_concat"*|*"CASE"*) ;;                # derived expressions
        # NOTE there is no exemption for a quote. The first version had one — "literals" —
        # and it swallowed `COALESCE(day, '') AS day`, which is the COMMON shape here and
        # unsafe: COALESCE picks the blob, not the fallback, because a blob is not NULL. It
        # hid five crashing commands the behavioural sweep then found anyway. That is the
        # failure this file's own header warns about, written into the file on the first
        # draft: an exemption list widened until the gate means nothing.
        *)
          printf '%-24s %-22s %s\n' "$(basename "$f")" "$alias" "$(printf '%s' "$tail_expr" | tail -c 46)" >> "$tmp/problems" ;;
      esac
    done < "$tmp/exprs"
  done < "$tmp/aliases"
done

# Asserted exactly, not as a floor. A gate whose enumeration silently matches nothing prints
# the same clean line a healthy tree prints — which is how the defect it guards got here.
EXPECT_DECODES=49
if [ "$decodes" != "$EXPECT_DECODES" ]; then
  echo "blob-safety: inspected $decodes Sqlite.str decodes, expected $EXPECT_DECODES."
  echo "blob-safety: if that change is intended, update the number in the same commit;"
  echo "blob-safety: if it is not, the decode scan stopped matching and this gate is blind."
  exit 1
fi

n=$(wc -l < "$tmp/problems" | tr -d ' ')
if [ "$n" -gt 0 ]; then
  echo "blob-safety: $n TEXT decode(s) read a column that is not CAST to TEXT"
  echo
  sort -u "$tmp/problems"
  echo
  echo "A blob in any of these crashes the reading command with internal_error (#307)."
  echo "Wrap the projection: COALESCE(CAST(<col> AS TEXT), '') AS <alias>"
  exit 1
fi
echo "blob-safety: $decodes TEXT decodes, every projection CAST to TEXT"
